### ISSUE TITLE
Build problems with am__api_version='1.15'

### ISSUE THREAD

**Issue by forsetti** [Jasig/mod_auth_cas#91]
Reported by @dhawes 

"configure" includes "am__api_version='1.15'", causing a problem building on systems with automake<1.15

autoreconf fixes configure to use local version

am__api_version should be effectively ignored (vi 'missing' script) unless a rebuild of configure is triggered.

Conversation on commit 38adbaec

**Comment by forsetti** [comment]
Continuing to bang my head against this one.
http://www.hep.by/gnu/automake/maintainer_002dmode.html

The problem is because creation timestamps are not preserved via Git, and
so a rebuild is triggered.  A /full/ rebuild using autoreconf with work
file. but the automatic automake-only rebuild will fail if the local
automake version is different than the original maintainer.

Choices:
* Enable AM_MAINTAINER_MODE([enable]), allowing explicit use of
"--disable-maintainer-mode"
to prevent auto-rebuild (note that AM_MAINTAINER_MODE([disable]) is
apparently strongly frowned upon)
* Purge autoconf artifacts (configure, Makefile.in, etc) from the project
completely, so all builds must begin with autoreconf -ifv (@pames tried to
convince me of this path years ago, but I was stubborn)
* Provide a timestamp-updating script to fake out the build

I'm struggling with right answer.  For now, please start your rebuilds with
"autoreconf -ivf" to leverage your local auto* tools.  I will get this
figured out shortly, and then we'll release 1.1.

38adbaec

**Comment by forsetti** [comment]
@dhawes Could you please try the "maintainer-mode-test" branch of my repo?
https://github.com/forsetti/mod_auth_cas/tree/maintainer-mode-test

I have set "AM_MAINTAINER_MODE([disable]) ".  While this is generally discouraged, I am making the assumption that any m-a-c developer that modifies autotools input (configure.ac, Makefile.am, *.m4, etc) will run 'autoreconf -ivf' to regen the artifacts.

**Comment by forsetti** [comment]
FYI - I've built a docker image to automatically build and run m-a-c tests on Trusty and CentOS7
https://github.com/forsetti/maccheck-docker/

**Comment by dhawes** [comment]
The maintainer-mode-test branch configures and makes without any intervention on my part. Looks good.

**Comment by dhawes** [comment]
A user reported the following on cas-user:

https://groups.google.com/a/apereo.org/forum/#!topic/cas-user/ajF3AUVCT6s

My initial thought was that they had an old version before this was merged, but I have confirmed it on Debian 8 as well as Ubuntu 14.04. I am confused by this because I tested this on Ubuntu, and I make it a point to always clone the repository before testing these things. I guess it seems more likely that I goofed (on multiple machines) than something else?

Looking at some other ways projects handle this (http://git.savannah.gnu.org/cgit/gawk.git/tree/bootstrap.sh), I'm wondering if a simple 'touch *' in configure has any negatives.
